version: '3'
services:
  worker1:
    build: .
    environment:
      - self=1
      - count=16
    depends_on:
      - redis
  worker2:
    build: .
    environment:
      - self=2
      - count=16
    depends_on:
      - redis
  worker3:
    build: .
    environment:
      - self=3
      - count=16
    depends_on:
      - redis
  worker4:
    build: .
    environment:
      - self=4
      - count=16
    depends_on:
      - redis
  worker5:
    build: .
    environment:
      - self=5
      - count=16
    depends_on:
      - redis
  worker6:
    build: .
    environment:
      - self=6
      - count=16
    depends_on:
      - redis
  worker7:
    build: .
    environment:
      - self=7
      - count=16
    depends_on:
      - redis
  worker0:
    build: .
    environment:
      - self=0
      - count=16
    depends_on:
      - redis
  worker8:
    build: .
    environment:
      - self=8
      - count=16
    depends_on:
      - redis
  worker9:
    build: .
    environment:
      - self=9
      - count=16
    depends_on:
      - redis
  worker10:
    build: .
    environment:
      - self=10
      - count=16
    depends_on:
      - redis
  worker11:
    build: .
    environment:
      - self=11
      - count=16
    depends_on:
      - redis
  worker12:
    build: .
    environment:
      - self=12
      - count=16
    depends_on:
      - redis
  worker13:
    build: .
    environment:
      - self=13
      - count=16
    depends_on:
      - redis
  worker14:
    build: .
    environment:
      - self=14
      - count=16
    depends_on:
      - redis
  worker15:
    build: .
    environment:
      - self=15
      - count=16
    depends_on:
      - redis
  redis:
    image: "redis:alpine"